services:

  config-server:
    image: "bharatkumaradapa/configserver:v6"
    container_name: configserver-ms
    ports:
      - "7000:7000"
    healthcheck:
      test: "curl --fail --silent localhost:7000/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config
      
  eurekaserver:
    image: "bharatkumaradapa/eurekaserver:v6"
    container_name: eurekaserver-ms
    ports:
      - "8761:8761"
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
    
  accounts:
    image: "bharatkumaradapa/accounts:v6"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans:
    image: "bharatkumaradapa/loans:v6"
    container_name: loans-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  cards:
    image: "bharatkumaradapa/cards:v6"
    container_name: cards-ms
    ports:
      - "8070:8070"
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  zettabank:
    driver: "bridge"

