spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: Bharat@10
    url: 'jdbc:postgresql://localhost:5432/db_material_inspection?currentSchema=mat_isp                 '
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
logging:
  file:
    name: logs/material-inspection_logs.log
  pattern:
    console: "%d %-5level %logger : %msg%n" 
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"  
  level:
    ROOT: INFO  
          
zettainsp:
  messages:
    saveSuccess: Saved Successfully
    saveFail: Save Failed
    updateSuccess: Updated Successfully
    updateFail: Update Failed
    deleteSuccess: Deleted Successfully
    deleteFail: Delete Failed