spring:
  config:
    import:
      "optional:configserver:http://localhost:7000/"
   
  application:
   name: "eurekaserver"
 
management:
  endpoints:
    web:
      exposure:
        include: "*"
 
  