server:
  port: 8070
spring:
  profiles:
    active: "qa"
  application:
    name: "cards"
  datasource:
    url: jdbc:h2:mem:cardsdb
    driverClassName: org.h2.Driver
    username: admin
    password: 1234
  
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
     "optional:configserver:http://localhost:7000/"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
   shutdown:
     enabled: true
  info:
   env:
    enabled: true
eureka:
 instance:
  prefer-ip-address: true
  appname: cards
 client:
   fetch-registry: true
   registerWithEureka: true
   serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    
info:
 app:
  name: "cards"
  description: "Zetta Application cards microservice"
  version: "1.0.0"
  