server:
  port: 8070
spring:
  application:
    name: "orders"
  datasource:
    url: jdbc:h2:mem:ordersdb
    driverClassName: org.h2.Driver
    username: admin
    password: root
  
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true

